# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:10.13

    working_directory: ~/jakbyco-gatsby

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Gatsby Build
          command: ./node_modules/.bin/gatsby build

      - persist_to_workspace:
          root: .
          paths:
            - public
      - run:
          name: check paths
          command: pwd && ls -al
  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: public
      - run:
          name: check files
          command: |
            pwd && ls -al

      - run:
          name: Deploy Over SSH
          command: |
            scp -P $SSH_PORT -r ~/public/ $SSH_USER@$SSH_HOST$SSH_PATH
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
